### ISSUE TITLE
 Conflicts with other mods.

### ISSUE THREAD

**Issue by kirito5572** [Pitan76/MCPitanLibarch#16]
In MC 1.20.4, fabric loader 0.15.11, fabric api 0.97.1, MCPitanLib 2.2.8, CICADA 0.8.1 
isn't crash.

But, MC 1.21, fabric loader 0.15.11, fabric api 0.100.4, MCPitanLib 2.2.8, CICADA 0.8.1 crash

Is there any code different from MC 1.20.4(2.2.8) when upgrading to MC 1.21(2.2.8)? If not, I report it to CICADA.

[latest.log](https://github.com/user-attachments/files/16042123/latest.log)

**Comment by kirito5572** [comment]
attaching only the parts with errors.
```
[05:27:53] [Render thread/ERROR]: Critical injection failure: LVT in net/minecraft/class_1863::method_20705(Ljava/util/Map;Lnet/minecraft/class_3300;Lnet/minecraft/class_3695;)V has incompatible changes at opcode 118 in callback mcpitanlib-common.mixins.json:RecipeManagerMixin from mod mcpitanlib->@Inject::mcpitanlib$invokeApply(Ljava/util/Map;Lnet/minecraft/class_3300;Lnet/minecraft/class_3695;Lcom/google/common/collect/ImmutableMultimap$Builder;Lcom/google/common/collect/ImmutableMap$Builder;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V.
 Expected: [Lcom/google/common/collect/ImmutableMap$Builder;, Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;]
    Found: [Lcom/google/common/collect/ImmutableMultimap$Builder;, Lcom/google/common/collect/ImmutableMap$Builder;]
Available: [Lcom/google/common/collect/ImmutableMultimap$Builder;, Lcom/google/common/collect/ImmutableMap$Builder;, Lnet/minecraft/class_6903;, Ljava/util/Iterator;]
[05:27:53] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1863 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1863 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_634.<init>(class_634.java:379) ~[client-intermediary.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayNetworkHandler.<init>(DummyClientPlayNetworkHandler.java:106) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayNetworkHandler.getInstance(DummyClientPlayNetworkHandler.java:61) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientWorld.<init>(DummyClientWorld.java:22) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientWorld.getInstance(DummyClientWorld.java:16) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayerEntity.<init>(DummyClientPlayerEntity.java:43) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayerEntity.getInstance(DummyClientPlayerEntity.java:38) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.showmeyourskin.ShowMeYourSkinClient.lambda$onInitializeClient$1(ShowMeYourSkinClient.java:41) ~[show-me-your-skin-1.11.1+1.21.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.1+8f3583aed1-e56ba4d7ddcf6ff8.jar:?]
	at net.minecraft.class_310.handler$bco000$fabric-lifecycle-events-v1$onStart(class_310.java:6694) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) ~[1.21-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_634.<init>(class_634.java:379) ~[client-intermediary.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayNetworkHandler.<init>(DummyClientPlayNetworkHandler.java:106) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayNetworkHandler.getInstance(DummyClientPlayNetworkHandler.java:61) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientWorld.<init>(DummyClientWorld.java:22) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientWorld.getInstance(DummyClientWorld.java:16) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayerEntity.<init>(DummyClientPlayerEntity.java:43) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayerEntity.getInstance(DummyClientPlayerEntity.java:38) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.showmeyourskin.ShowMeYourSkinClient.lambda$onInitializeClient$1(ShowMeYourSkinClient.java:41) ~[show-me-your-skin-1.11.1+1.21.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.1+8f3583aed1-e56ba4d7ddcf6ff8.jar:?]
	at net.minecraft.class_310.handler$bco000$fabric-lifecycle-events-v1$onStart(class_310.java:6694) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) ~[1.21-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1863::method_20705(Ljava/util/Map;Lnet/minecraft/class_3300;Lnet/minecraft/class_3695;)V has incompatible changes at opcode 118 in callback mcpitanlib-common.mixins.json:RecipeManagerMixin from mod mcpitanlib->@Inject::mcpitanlib$invokeApply(Ljava/util/Map;Lnet/minecraft/class_3300;Lnet/minecraft/class_3695;Lcom/google/common/collect/ImmutableMultimap$Builder;Lcom/google/common/collect/ImmutableMap$Builder;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V.
 Expected: [Lcom/google/common/collect/ImmutableMap$Builder;, Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;]
    Found: [Lcom/google/common/collect/ImmutableMultimap$Builder;, Lcom/google/common/collect/ImmutableMap$Builder;]
Available: [Lcom/google/common/collect/ImmutableMultimap$Builder;, Lcom/google/common/collect/ImmutableMap$Builder;, Lnet/minecraft/class_6903;, Ljava/util/Iterator;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:544) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_634.<init>(class_634.java:379) ~[client-intermediary.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayNetworkHandler.<init>(DummyClientPlayNetworkHandler.java:106) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayNetworkHandler.getInstance(DummyClientPlayNetworkHandler.java:61) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientWorld.<init>(DummyClientWorld.java:22) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientWorld.getInstance(DummyClientWorld.java:16) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayerEntity.<init>(DummyClientPlayerEntity.java:43) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.cicada.api.cursed.DummyClientPlayerEntity.getInstance(DummyClientPlayerEntity.java:38) ~[cicada-lib-0.8.1+1.21-and-above.jar:?]
	at nl.enjarai.showmeyourskin.ShowMeYourSkinClient.lambda$onInitializeClient$1(ShowMeYourSkinClient.java:41) ~[show-me-your-skin-1.11.1+1.21.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:35) ~[fabric-lifecycle-events-v1-2.3.1+8f3583aed1-e56ba4d7ddcf6ff8.jar:?]
	at net.minecraft.class_310.handler$bco000$fabric-lifecycle-events-v1$onStart(class_310.java:6694) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) ~[1.21-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 2 more
```

**Comment by kirito5572** [comment]
If I don't use 2.2.8, and use 2.2.7, it's fine. 

There seems to be a problem in 2.2.8.
